### ISSUE TITLE
Auto-deploy and review apps are broken

### ISSUE THREAD

**Issue by mrcasals** [AjuntamentdeBarcelona/decidim-design#107]
#### :tophat: User Story
I grouped both things in the same issue since I think they are both related. Could this be due to a broken Heroku integration, @josepjaume? 

I think I don't have enough permissions in order to fix this.

#### :dart: Acceptance criteria
- When a new commit is pushed to a PR, a review app should be created
- When a PR is merged, `master` branch should be automatically deployed. 

#### :pushpin: Related issues
None.

**Comment by mrcasals** [comment]
Looks like Heroku was having a system maintenance for these services:

https://status.heroku.com/incidents/1015

Let's close this and reopen it if we keep encountering problems.

**Comment by mrcasals** [comment]
Looks like it's still broken:

![](https://i.imgur.com/wG3M3f7.png)

**Comment by josepjaume** [comment]
Fixed!
