### ISSUE TITLE
Refactor loading of modules in Sass

### ISSUE THREAD

**Issue by htmlboy** [AjuntamentdeBarcelona/decidim-design#114]
#### :tophat: User Story
There are several problems related with the way we're loading Sass modules (with an asterisk, meaning "all the files inside the folder, alphabetically"): we can't control the CSS cascade, define dependant modules or share variables.

We'd need to load these files from a list. The downside of this would be to manually update this list, which is a normal practice in other developing environments. The benefits would be a granulated control of the CSS, the module order and the ability to create smaller files with shared variables (as a separated "card-list" file that can use the variables in "cards" file).

#### :dart: Acceptance criteria
- /modules/ are loaded from a list (/modules/_modules.scss) instead of the * selector.

#### :pushpin: Related issues
#115

**Comment by htmlboy** [comment]
@josepjaume We're running into a lot of problems because of this. Could you please confirm if this change wouldn't cause any problems?

**Comment by josepjaume** [comment]
Sorry! I definitely agree on that wildcard imports are generally a bad idea. Explictly specifying dependencies in each file es even a better way to go (that is, assuming the required file doesn't spit any extra css and only includes mixins/functions), but I'm also on board in importing from a list.

**Comment by htmlboy** [comment]
Cool, moving this to the backlog then :-)
