### ISSUE TITLE
Deprecated `foundation-responsive-video`

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#123]
#### :tophat: User Story
When compiling assets (but for some reason only on `decidim`) these warnings are being thrown:

```
WARNING: This mixin is being replaced by foundation-responsive-embed(). foundation-flex-video() will be removed in Foundation 6.4.
       Backtrace:
       vendor/bundle/ruby/2.4.0/gems/foundation-rails-6.3.0.0/vendor/assets/scss/components/_responsive-embed.scss:59, in mixin `foundation-flex-video`
       vendor/bundle/ruby/2.4.0/bundler/gems/decidim-367143c1f91b/decidim-admin/app/assets/stylesheets/decidim/admin/_foundation_and_overrides.scss:30
```

Looks like it started happening after the foundation 6.3 upgrade.

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
No warnings are shown.

#### :pushpin: Related issues
*None*.

**Comment by htmlboy** [comment]
@josepjaume This looks like something that should be fixed in the /decidim/ code, right?

**Comment by josepjaume** [comment]
Oh my! This is only happening in admin!!! So sorry, totally on our side of things then!
