### ISSUE TITLE
Features menu does not wrap content

### ISSUE THREAD

**Issue by mrcasals** [AjuntamentdeBarcelona/decidim-design#133]
#### :tophat: User Story
Coming from https://github.com/AjuntamentdeBarcelona/decidim/issues/672

When the features menu has more content than what the width can handle, it hides the content:

![](https://i.imgur.com/OtOCym8.png)

In this case, the problem arises from a missing translation, that generates a really long name for one of the features, but features names can be customized, thus this problem can appear due to the user input. Also, note that a single feature can appear multiple times in a single process, so that can cause this problem again.

Thoughts?

#### :clipboard: Related documentation
None

#### :dart: Acceptance criteria
Content is wrapped in the features menu.

#### :pushpin: Related issues
None

**Comment by htmlboy** [comment]
Not exactly a bug. The menu in this screen size has an overflow scroll behaviour, making the navigation horizontally scrollable if it's long enough. It's better than wrapping (in this context). Also, menu links texts should have a max-length and a default to other language, if translations are missing. Thoughts @josepjaume ?

**Comment by josepjaume** [comment]
Oh ok, so what you're saying is this will turn into a scrollable panel on mac (the invisible scroll one) and to an ugly scroll bar on windows?

If that's the case, it's OK for me.

**Comment by htmlboy** [comment]
It's not super-ugly, but will be visible. Please consider if this is something that requires a redesign.

![captura de pantalla 2017-02-15 a las 12 32 26](https://cloud.githubusercontent.com/assets/468685/22972672/f6d1e276-f37a-11e6-97c5-440c3c5731e5.png)
