### ISSUE TITLE
Features menu not visible from mobile

### ISSUE THREAD

**Issue by carolromero** [AjuntamentdeBarcelona/decidim-design#134]
#### :tophat: User Story
When I try to access to a Process from a mobile phone I can't see the Features menu (Proposals, Meetings, etc.)

#### :dart: Acceptance criteria
I can see the Features menu when accessing from a mobile phone.

**Comment by mrcasals** [comment]
Moving to main `decidim` repo, thanks!

**Comment by mrcasals** [comment]
Solved at https://github.com/AjuntamentdeBarcelona/decidim/issues/682, will be available once we update Decidim here.

Closing the issue.
