### ISSUE TITLE
Hollow disabled buttons shouldn't highlight

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#137]
#### :tophat: User Story
We've found several use cases for disabled hollow buttons. The thing is: They highlight when hovered, which creates a false impression of "interactivity", while its main goal is actually to indicated otherwise.

Example:

![jan-31-2017 11-41-22](https://cloud.githubusercontent.com/assets/111746/22461633/53960fa0-e7aa-11e6-8397-5735fab30e24.gif)

Should we consider removing the highlight effect?

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
Disabled buttons don't appear to be interactive.

#### :pushpin: Related issues
*None*

**Comment by htmlboy** [comment]
This is a Foundation bug (try adding disabled class or attribute to hollow buttons in http://foundation.zurb.com/sites/docs/button.html ), but we could plan some sort of solution.
