### ISSUE TITLE
Intermediate state when adding items to the budget cart

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#138]
#### :tophat: User Story
We're disabling the buttons while the request to add a new budget to the cart is being made. This generates a weird padding issue.

**Note**: We've used a `button` instead of an `a` element because it makes more sense semantically and we can then leverage `rails'` mechanisms to auto-set the `disabled` property.

#### :clipboard: Related documentation
![](https://media.giphy.com/media/26gsaD6UQSZu5mmv6/giphy.gif)

#### :dart: Acceptance criteria
Buttons stay put when clicked.

#### :pushpin: Related issues
*None*

**Comment by htmlboy** [comment]
@josepjaume OK, so I wrote a comment yesterday and apparently I never published. I run some tests and the only thing that can cause this misalignment in decidim-design code is not the disable attribute nor being a button, but the removal of a class: `.budget--list__action`. So I suspect the same code that is adding the disabled state is removing this class. Could it be? I not, could you send me a staging link to test the origin of the issue?

**Comment by josepjaume** [comment]
@htmlboy this looks like it got fixed pseudo-accidentally in another PR 👍
