### ISSUE TITLE
Disabled buttons are transparent (and should be translucid)

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#145]
#### :tophat: User Story
Disabled buttons are transparent while they should be translucid. 

This bug re-appeared after trying to fix it in https://github.com/AjuntamentdeBarcelona/decidim-design/pull/122. Maybe because of a weird interaction with https://github.com/AjuntamentdeBarcelona/decidim-design/issues/137 ?

![transparent-buttons](https://cloud.githubusercontent.com/assets/111746/23020001/3ac0868e-f445-11e6-854c-6d6459d2674d.gif)

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
Buttons (and links with a button class) with a disabled attribute should be translucid, not transparent.

#### :pushpin: Related issues
* #122 
* #137

**Comment by htmlboy** [comment]
@josepjaume can you replace the `<input>` tag with a `<button>` tag and confirm there's still a problem? Foundation has a grey background for every disabled input by default (that's what you're seeing in the first place), and I'd prefer to not force specificity in `.button`styles if we can avoid it.
