### ISSUE TITLE
Cookie bar

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#58]
#### :tophat: User Story
In order to comply with EU's regulations, we should show a non-blocking, off-canvas cookie bar asking the user to accept the page's cookies.

#### :clipboard: Related documentation
- https://www.cookielaw.org/the-cookie-law/

#### :dart: Acceptance criteria
Users see a non-intrusive, informative cookie advise somewhere on the page.

#### :pushpin: Related issues
*None*

**Comment by rosa2** [comment]
And it should be also possible to work without cookies to be more inclusive. Also explain very exactly why the cookies are used (as for example for language).
