### ISSUE TITLE
Proposal creation form

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#59]
#### :tophat: User Story
In order for the user to be able to create proposals (and potentially other similar entities), we should expose a form to do that.

This form should include:

* Proposal title
* Proposal description
* Proposal category and subcategory
* Captcha

#### :clipboard: Related documentation
You can use the old `decidim.barcelona` as reference: https://decidim.barcelona/4/8/proposals/new

#### :dart: Acceptance criteria
Proposal forms include all the data that they'll afterwards be displayed on the proposal list.

#### :pushpin: Related issues
*None*.

**Comment by htmlboy** [comment]
PR created. The form can be checked in https://decidim-design-pr-66.herokuapp.com/new-proposal/

@josepjaume It still requires the Captcha code. Also, from a backend point of view:

- Categories and subcategories should appear only if available.
- Proposal description should be trimmed (maybe 250-300 chars?) in card view
- Title should have a max-length or be trimmed in card view
- Max-length of the textarea should be long enough to accommodate most proposals

**Comment by htmlboy** [comment]
Note: The form requires more hinting/information/placeholders.

**Comment by josepjaume** [comment]
Considering this closed!
