### ISSUE TITLE
Split styles into components

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#61]
#### :tophat: User Story
[Decidim is a rails application](https://github.com/AjuntamentdeBarcelona/decidim) that's split over several engines, each one with its associated functionalities & UI.

We should split the styles in the same shape, so we can easily update them in each engine when needed (and even automate this).

We should have separate styles for:

* Comments
* Proposals
* Debates
* Meetings
* Action plans

**Note**: We should also organize the page list so it matches that separation.

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
Stylesheets are split in several folders, each one for each engine.

#### :pushpin: Related issues
*None*

**Comment by htmlboy** [comment]
@josepjaume I need more information regarding this issue. The current build of the app stylesheet is this:

Load utils (with variables, mixins and general settings) > Load foundation libraries > Load modules --> create stylesheet.

Modules are separate pieces of interface: buttons.scss, comments.scss, flag.scss… Compound elements such as Comments use several shared modules like buttons or flag.

Shall we create a different processed stylesheet for each of these interface items, hence risking CSS overload? 
Or perhaps we're aiming for these stylesheets:
· all-elements-that-are-shared-and-loaded-in-every-case.css
· code-that-only-applies-to-comments.css
· code-that-only-applies-to-proposals.css
· code-that-only-applies-to-meetings.css
· code-that-only-applies-to-actions.css

**Comment by josepjaume** [comment]
It's a tricky subject. I think we should create a separate CSS file for every separate component (proposals, meetings, comments), but those separate CSS files would be compiled using SASS, importing mixins and configuration from `core`.

So, in the end, we'd have something like:

```
decidim.sass
proposals.sass
comments.sass
...
```

Inside comments, you'd find:

```sass
@import "decidim/config"; # Maybe variables, etc
@import "decidim/cards"; # Mixins relative to cards

# Specific comments code
```

Does this make sense to you? We risk a bit of CSS overloading, but a the same time, we can load CSS by pieces, depending on which functionality is active.

**Comment by htmlboy** [comment]
I've found some problems with this issue: almost everything is kinda core. Needs deeper discussion, moving it to the icebox.
