### ISSUE TITLE
Fix travis-ci build error 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-design#64]
#### :tophat: User Story

Travis-ci build is on error because of yarn package. 

> 
> E: Unable to locate package yarn
> The command "sudo apt-get install -y -qq yarn" failed and exited with 100 during .
> Your build has been stopped.

#### :clipboard: Related documentation

https://github.com/AjuntamentdeBarcelona/decidim-design/blob/master/.travis.yml

#### :dart: Acceptance criteria

It should be OK / green status

**Comment by josepjaume** [comment]
Fixed!
