### ISSUE TITLE
Comment reply button position

### ISSUE THREAD

**Issue by beagleknight** [AjuntamentdeBarcelona/decidim-design#69]
#### :tophat: User Story

We are implementing comment replies and we thought it's better to position the reply button under comment replies like this:

![image](https://cloud.githubusercontent.com/assets/106021/21139649/34234d82-c134-11e6-879f-164a546d9191.png)

Since the `comment__footer` div is the only one with padding we need to add a custom div or something to add space between the comment body and comment replies.

#### :clipboard: Related documentation
None

#### :dart: Acceptance criteria
The comment reply button is below comment replies and there is a space between comment body and comment replies.

#### :pushpin: Related issues
- https://github.com/AjuntamentdeBarcelona/decidim/pull/335

**Comment by josepjaume** [comment]
The reason behind this decision is that since `reply` is only available on the first 3 levels, it's easier for a user to keep engaged in a conversation if "reply" is shown at the bottom (instead of having to scroll up)
