### ISSUE TITLE
Make logo size flexible

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#70]
#### :tophat: User Story
When using an image instead of text as logo, it doesn't appear to be fluid. We should fix its height but not its weight, so it can accomodate any kind of logo.

#### :clipboard: Related documentation
*None*

#### :dart: Acceptance criteria
One can upload any kind of logo and will always appear the same height, despite of its width.

#### :pushpin: Related issues
*None*

**Comment by htmlboy** [comment]
Solved. PR: https://github.com/AjuntamentdeBarcelona/decidim-design/pull/91
