### ISSUE TITLE
Active states the alignment button in comments

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#86]
#### :tophat: User Story
Alignment buttons (in favor, neutral, against) don't have different "disabled", "focused" and "active" states, so using them becomes a bit confusing.

#### :clipboard: Related documentation
![dec-21-2016 18-38-34](https://cloud.githubusercontent.com/assets/111746/21399650/b9b48168-c7ac-11e6-8764-85772f68a132.gif)

#### :dart: Acceptance criteria
Setting an alignment for a comment is easy and not confusing xD

#### :pushpin: Related issues
*None*

**Comment by beagleknight** [comment]
The current neutral button is fake as well because I just duplicated one of the others 😝 . We need a good looking one with an icon as well 😄
