### ISSUE TITLE
Component: Participatory budget

### ISSUE THREAD

**Issue by josepjaume** [AjuntamentdeBarcelona/decidim-design#88]
#### :tophat: User Story
Participatory budgets act like a "shopping cart" for projects. Projects might be related to proposals).

#### :clipboard: Related documentation
Definition on `decidim`: https://github.com/AjuntamentdeBarcelona/decidim/issues/420

#### :dart: Acceptance criteria
Users can "shop" projects.

#### :pushpin: Related issues
*None*

**Comment by josepjaume** [comment]
@htmlboy @martuishere  relative to timings: It's quite critical that we can ship this during the next week, so we can develop it on the next one. Do you think that's possible?

**Comment by htmlboy** [comment]
@josepjaume definitely possible, indeed!

**Comment by andreslucena** [comment]
How are we with this guys? Do you need anything from us?

**Comment by htmlboy** [comment]
@andreslucena We already have a working prototype. You can check it in https://decidim-design-pr-116.herokuapp.com/proposals-budget/

**Comment by josepjaume** [comment]
Niiiiice!! I love it overall, nice job!! Should we show the project's short description in the view list?

**Comment by andreslucena** [comment]
Ok, Thanks!  
It would be nice to have the progress bar fixed on scroll (for instance http://codepen.io/chriscoyier/full/AdaKr/) 
We shouldn't show the project's short description for space concerns.

**Comment by htmlboy** [comment]
@josepjaume: we could, but since the Ajuntament will be already writing the titles of the projects, we expect them to be informative enough to skip the description, and therefore displaying more items in a view.

@andreslucena: this is something that we should consider, definitely; we're a bit worried about the overall experience and mobile layout. We'll be working in the feedback and use cases next, and see if we can accommodate something like that.

**Comment by htmlboy** [comment]
Design updated:

Progress list, with sticky progress bar: https://decidim-design-pr-116.herokuapp.com/projects-budget/
Project view: https://decidim-design-pr-116.herokuapp.com/project-budget-view/
Confirm voting: https://decidim-design-pr-116.herokuapp.com/projects-budget-confirm/
"You can't add more projects to your budget": https://decidim-design-pr-116.herokuapp.com/projects-budget-excess/
